name: fhir-with-ossloader

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TEMP_DIR_PATH: './tmp'
  OSS_FHIR_LOADER_DEPLOY_SCRIPT: 'deployFhirBulk.bash '
  FHIR_ENDPT_DOMAIN: '.fhir.azurehealthcareapis.com'
  SYNTHEA_DATA_TYPE: ${{secrets.SYNTHEA_DATA_TYPE}}

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:

  # job1: deploy the ahds workspace with a fhir service
  deploy-fhir-infra:
    #if: ${{ false }} #disables the job
    runs-on: ubuntu-latest
    environment: sample
    outputs:
      fhirWorkspaceName: ${{ steps.get-resource-names.outputs.fhirWorkspaceName }} 
      fhirName: ${{ steps.get-resource-names.outputs.fhirName }}

    steps:

      # checkout 
    - uses: actions/checkout@v3

      # log into Azure
    - name: az-login
      uses: Azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # hash the resource group's ID so it's unique but also repeatable
      # steps: 
      # 1. retrieve the resouceGroup's id property
      # 2. hash the id and take the first 8 chars of the hash
      # 3. set the output using the hash substring
    - name: generate resource names 
      id: get-resource-names
      run: |
        rsGroupId=$(az group list --query "[?name=='${{ secrets.AZURE_RG }}'].id" -o tsv)        
        suffix=$(echo -n $rsGroupId | shasum | cut -c1-8)

        echo "fhirWorkspaceName=ws$suffix" >> $GITHUB_OUTPUT
        echo "fhirName=fhir$suffix" >> $GITHUB_OUTPUT
        echo "kvName=kv$suffix" >> $GITHUB_OUTPUT
        echo "cicdSPObjId=$(az ad sp show --id "${{secrets.AZURE_CLIENT_ID}}" --query "id" -o tsv)" >> $GITHUB_OUTPUT
        echo "ossFhirLoaderDeployPrefix=ofl$suffix" >> $GITHUB_OUTPUT
        echo "rgLocation=$(az group show -g "fhir-in-a-box-v3" --query "location" -o tsv)" >> $GITHUB_OUTPUT

        unset rsGroupId
        unset suffix

    - name: create fhir client app/SP for the fhir-loader
      id: create-fhir-client-app
      run: |
        fhirClientName="${{steps.get-resource-names.outputs.ossFhirLoaderDeployPrefix}}-fhir-app"
        fhirServiceName="${{steps.get-resource-names.outputs.fhirWorkspaceName}}/${{steps.get-resource-names.outputs.fhirName}}" 
        replyUrls="https://oauth.pstmn.io/v1/callback" # postman client for now
        healthCareAPIsPermissionAppId="4f6778d8-5aef-43dc-a1ff-b073724b9495" # should be referenced in ms_docs
        fhirDataContributorRole="FHIR Data Contributor"
        
        echo "...creating fhir-loader aad app.."
        fhirClientAppId=$(az ad app create --display-name $fhirClientName --web-redirect-uri $replyUrls --query "appId" -o tsv) 
        
        sleep 10
        
        echo "...creating fhir-loader aad SP.."
        az ad sp create --id $fhirClientAppId
        fhirClientAppSecret=$(az ad app credential reset --id $fhirClientAppId --display-name "client-secret" --query password -o tsv)

        echo "...assigning SP a fhir rbac role to the fhir service "
        fhirClientObjectId=$(az ad sp list --display-name "$fhirClientName" --query "[].id" -o tsv)
        fhirResourceId=$(az resource list --name "$fhirServiceName" --query "[].id" -o tsv)

        roleAssignId1=$(az role assignment create \
            --assignee "$fhirClientObjectId" \
            --role "$fhirDataContributorRole" \
            --scope $fhirResourceId --query "id" -o tsv)

        echo "......adding Azure Healthcare APIs permission"
        hcApisUserImpersonationScopeId=$(az ad sp list --filter "appId eq '$healthCareAPIsPermissionAppId'" --query "[].oauth2PermissionScopes[?value=='user_impersonation'].id" -o tsv)

        # check if the permission has already been added 
        isHCApiExists=$(az ad app permission list --id "$fhirClientAppId" --query "[].resourceAccess[?id=='$hcApisUserImpersonationScopeId'].id" -o tsv)
        if [ -z  "$isHCApiExists" ] 
        then 
            # add the hcAPI permission and user_impersonation scope
            az ad app permission add \
            --id $fhirClientAppId \
            --api $healthCareAPIsPermissionAppId \
            --api-permissions $hcApisUserImpersonationScopeId=Scope
        else
            echo ".........Azure Healthcare APIs permission already exists, skipping permission add."
        fi

        echo "fsClientId=$fhirClientAppId" >>$GITHUB_OUTPUT 
        echo "fsClientSecret=$fhirClientAppSecret" >>$GITHUB_OUTPUT 
  
      # deploy fhir service and related workloads       
    - name: deploy-fhir-infra
      #if: ${{ false }} #disables the step
      uses: azure/arm-deploy@v1.0.9
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./bicep/ahds-fhir-with-ossfhirloader.bicep
        parameters: 'workspaceName=${{steps.get-resource-names.outputs.fhirWorkspaceName}}
        fhirName=${{steps.get-resource-names.outputs.fhirName}}
        kvName=${{steps.get-resource-names.outputs.kvName}}
        cicdServicePrincipalObjectId=${{steps.get-resource-names.outputs.cicdSPObjId}}
        fsUrlSecretValue=https://${{needs.deploy-fhir-infra.outputs.fhirWorkspaceName}}-${{needs.deploy-fhir-infra.outputs.fhirName}}${{env.FHIR_ENDPT_DOMAIN}}
        fsResourceSecretValue=https://${{needs.deploy-fhir-infra.outputs.fhirWorkspaceName}}-${{needs.deploy-fhir-infra.outputs.fhirName}}${{env.FHIR_ENDPT_DOMAIN}}
        fsTenantIdSecretValue=${{secrets.AZURE_TENANT_ID}}
        fsClientIdSecretValue=${{steps.create-fhir-client-app.outputs.fsClientId}}
        fsClientSecretSecretValue=${{steps.create-fhir-client-app.outputs.fsClientSecret}}'

      # download oss fhir loader deploy script 
      # 1. comment out the user prompts, e.g. 'read -p...'
    - name: download oss fhir loader deploy script
      run: |
        mkdir ${{ env.TEMP_DIR_PATH }}
        curl -L https://raw.githubusercontent.com/microsoft/fhir-loader/main/scripts/deployFhirBulk.bash \
         --output ${{ env.TEMP_DIR_PATH }}/${{ env.OSS_FHIR_LOADER_DEPLOY_SCRIPT }}
        sed -i '/.*read -p/ s/./#&/' ${{ env.TEMP_DIR_PATH }}/${{ env.OSS_FHIR_LOADER_DEPLOY_SCRIPT }}       

      # deploy fhir loader
    - name: deploy-oss-fhir-loader
      run: |
        cd ${{ env.TEMP_DIR_PATH }}
        bash ./${{ env.OSS_FHIR_LOADER_DEPLOY_SCRIPT }} \
         -i ${{secrets.AZURE_SUBSCRIPTION_ID}} \
         -g ${{secrets.AZURE_RG}} \
         -l ${{steps.get-resource-names.outputs.rgLocation}} \
         -n ${{steps.get-resource-names.outputs.ossFhirLoaderDeployPrefix}} \
         -k ${{steps.get-resource-names.outputs.kvName}} \
         -o "fhir"
        

  # job2: seed fhir service with synthea data 
  seed-with-synthea-data:
    if: ${{ false }} #disables the step
    needs: [deploy-fhir-infra]
    runs-on: ubuntu-latest
    environment: sample

    steps:

      # checkout 
    - uses: actions/checkout@v3

      # log into Azure
    - name: az-login
      uses: Azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # Install synthea and generate data
    - name: install-jdk
      uses: actions/setup-java@v3.8.0
      with:
        distribution: 'microsoft' 
        java-version: '17'
    
      # generate Synthea build import either as FHIR bundles (transactional or batch), ndjson FHIR bundles,  or compressed (.zip) FHIR Bundles
      # ref for synthea options: https://github.com/synthetichealth/synthea/wiki/HL7-FHIR
    # - name: install-and-run-synthea
    #   run: |
    #     java -version
    #     mkdir ${{ env.TEMP_DIR_PATH }}
    #     curl -L https://github.com/synthetichealth/synthea/releases/download/master-branch-latest/synthea-with-dependencies.jar \
    #      --output ${{ env.TEMP_DIR_PATH }}/${{ env.SYNTHEA_JAR_NAME }}
        
    #     syntheaOptions=''
    #     if ['zip' = ${{ env.SYNTHEA_DATA_TYPE }}] 
    #     then
    #       echo "...generating synthea zip files..."
    #       $syntheaOptons=''
    #     elif ['ndson' = ${{ env.SYNTHEA_DATA_TYPE }}]
    #     then
    #       echo "...generating synthea ndjson files..."
    #       $syntheaOptons='--exporter.fhir.bulk_data=true'
    #     else
    #       echo "...generating synthea bundle files..."
    #       $syntheaOptons=''
    #     fi

    #     cd ${{ env.TEMP_DIR_PATH }}
        
    #     java -jar ${{ env.SYNTHEA_JAR_NAME }} \
    #      -m "${{ secrets.SYNTHEA_MODULE_NAME }}" \
    #      -p ${{ secrets.SYNTHEA_PATIENTS_NUM }} \
    #      $syntheaOptons

    #     ls -l
    
    #   # azcopy synthea data to target storage account
    # - name: azcopy-to-storage
    #   run: |
    #     ls -l
    #     cd ${{ env.TEMP_DIR_PATH }}
    #     wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
    #     ls -l
    #     azcopy login --service-principal --application-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}
    #     azcopy login status
    #     echo "STORAGEACCT: https://${{needs.deploy-fhir-infra.outputs.import-storage-acct-name}}.blob.core.windows.net/${{needs.deploy-fhir-infra.outputs.bulk-import-blob-container-name}}/"
    #     azcopy cp "./output/fhir/*.*" "https://${{needs.deploy-fhir-infra.outputs.import-storage-acct-name}}.blob.core.windows.net/${{needs.deploy-fhir-infra.outputs.bulk-import-blob-container-name}}/" --recursive=true
    #   env: 
    #     AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
