# This is a basic workflow to help you get started with Actions

name: scratchpad

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IS_NDJSON_BULKLOAD: ${{secrets.IS_NDJSON_BULKLOAD}}
  IS_BUNDLE_COMPRESSED: ${{secrets.IS_BUNDLE_COMPRESSED}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: sample


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: test-folded-style
        if: ${{ false }} #disables the step
        id: test-folded-style
        run: >
          aUrl="https://abc.com";
          importModeBody="{
            \"resourceType\": \"Parameters\",
            \"parameter\": [
              {\"name\":\"inputFormat\", \"valueString\":\"application/fhir+ndjson\"},
              {\"name\":\"mode\", \"valueString\":\"InitialLoad\"},
              {\"name\":\"input\",
                  \"part\": [
                    {\"name\":\"type\", \"valueString\":\"Patient\"},
                    {\"name\":\"url\", \"valueUri\":\"$aUrl/Patient.ndjson\"}
                  ]
              },
            ]
          }";
          
          echo "the importModeBody is: $importModeBody";
          echo "second echo only";
          var2="BAHH";
          echo "firstVar=$var2" >> $GITHUB_OUTPUT;
          echo "this is the last echo!";
          
      - name: access the var above
        if: ${{ false }} #disables the step
        run: |
          echo "the var above is ${{steps.test-folded-style.outputs.firstVar}}"
          
      - name: test multiline
        if: ${{ false }} #disables the step
        run: |
          aUrl="https://abc.com"
          importModeBody="{
            \"resourceType\": \"Parameters\",
            \"parameter\": [
              {\"name\":\"inputFormat\", \"valueString\":\"application/fhir+ndjson\"},
              {\"name\":\"mode\", \"valueString\":\"InitialLoad\"},
              {\"name\":\"input\",
                  \"part\": [
                    {\"name\":\"type\", \"valueString\":\"Patient\"},
                    {\"name\":\"url\", \"valueUri\":\"$aUrl/Patient.ndjson\"}
                  ]
              },
            ]
          }"
          echo "the importModeBody is: $importModeBody";
          echo $aUrl/'$import'
          
      - name: test jq
        if: ${{ false }} #disables the step
        run: |
          response="$(cat <<EOF
          HTTP/2 202
          date: Tue, 20 Dec 2022 19:46:50 GMT 
          server: Kestrel
          content-location: https://ws09d55b6d-fhir09d55b6d.fhir.azurehealthcareapis.com/_operations/import/21
          content-length: 0
          x-request-id: 3921cb6432178c03de589cb97e77d6f3
          strict-transport-security: max-age=31536000; includeSubDomains
          x-content-type-options: nosniff
          x-frame-options: SAMEORIGIN
          content-security-policy: frame-src 'self';
          EOF
          )"
          echo $response
          callbackUrl=$(echo $response | sed -n -e 's/^.*content-location: //p' | sed -e 's/\n$//') \
          echo "this is the url: '$callbackUrl'"
      
        
      - name: sed test
        id: sed-test
        if: ${{ false }} #disables the step
        run: |
          fhirUrl=https://ws736c3e4c-fhir736c3e4c.fhir.azurehealthcareapis.com
          echo $fhirUrl/'$import'
          importModeBody="{
            \"resourceType\": \"Parameters\",
            \"parameter\": [
              {\"name\":\"inputFormat\", \"valueString\":\"application/fhir+ndjson\"},
              {\"name\":\"mode\", \"valueString\":\"InitialLoad\"},
              {\"name\":\"input\",
                  \"part\": [
                    {\"name\":\"type\", \"valueString\":\"Patient\"},
                    {\"name\":\"url\", \"valueUri\":\"https://fhirimpsa736c3e4c.blob.core.windows.net/importsrc/Patient.ndjson\"}
                  ]
              },
            ]
          }"
          #echo "importModeBody=$importModeBody"
          
          echo "...calling import endpoint..."
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} 
          token="$(az account get-access-token --resource=$fhirUrl --query accessToken --output tsv)"
          response=$(curl -i -d "$importModeBody" -H "Prefer:respond-async" -H "Content-Type:application/fhir+json" -H "Authorization: Bearer $token" -X POST $fhirUrl/'$import')
          printf "...response: \n$response"
          
          callbackUrl=$(echo "$response" | sed -n 's/^content-location:[[:space:]]//p' | sed -e 's/\r//')
          echo "...calling '$callbackUrl' in a loop to retrieve import status..."

          counter=1
          while [ -z "$importResult" ]; do
            sleep 20
            echo "...attempt #: $counter" 
            importResult=$(curl -s -X GET "$callbackUrl" -H "Authorization: Bearer $token" | jq .)
            ((counter++))
          done

          printf "final result: \n$importResult"

        #callbackResp=$(curl -s -X GET ${{steps.sed-test.outputs.importCallBackUrl}} -H "Authorization: Bearer $token")   
      - name: test curl
        if: ${{ false }} #disables the step
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} 
          fhirUrl=https://ws736c3e4c-fhir736c3e4c.fhir.azurehealthcareapis.com
          token="$(az account get-access-token --resource=$fhirUrl --query accessToken --output tsv)"
          #output1=$(curl --fail --connect-timeout 3 --retry 3 -X GET ${{steps.sed-test.outputs.importCallBackUrl}} -H "Authorization: Bearer $token" -H "Accept: application/json" | jq .)
          #echo $output1
          #curl --silent --output test.txt -X GET ${{steps.sed-test.outputs.importCallBackUrl}} -H "Authorization: Bearer $token"
          #cat test.txt
          #echo '{"foo": 0}' | jq .

          echo "... hard coded value ..."
          curl -X GET https://ws736c3e4c-fhir736c3e4c.fhir.azurehealthcareapis.com/_operations/import/45 -H "Authorization: Bearer $token" | jq .
          echo ".... with var replacement ..."
          var1="https://ws736c3e4c-fhir736c3e4c.fhir.azurehealthcareapis.com/_operations/import/45"
          curl -X GET $var1 -H "Authorization: Bearer $token" | jq .
          
      - name: test-if
        run: |
          isNdjsonFormat="${{env.IS_NDJSON_BULKLOAD}}" 
          isBundleCompressed="${{env.IS_BUNDLE_COMPRESSED}}"

          if [ "$isNdjsonFormat" = "true" ]; then
            echo "...Creating bulk (ndjson) bundles."
          else
            echo "...Creating transaction bundles"
          fi

          if [ "$isBundleCompressed" = "true" ]; then
            echo "...bundles are compressed aka zipped."
          else
            echo "...bundles are non compressed."
          fi

          if [[ "$isNdjsonFormat" = "false" && "$isBundleCompressed" = "true" ]]; then
            echo "...zipping fhir bundles to ./output/zip folder ..."
          fi
