# This is a basic workflow to help you get started with Actions

name: scratchpad

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.test-folded-style.outputs.firstVar}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: test-folded-style
        id: test-folded-style
        run: >
          aUrl="https://abc.com";
          importModeBody="{
            \"resourceType\": \"Parameters\",
            \"parameter\": [
              {\"name\":\"inputFormat\", \"valueString\":\"application/fhir+ndjson\"},
              {\"name\":\"mode\", \"valueString\":\"InitialLoad\"},
              {\"name\":\"input\",
                  \"part\": [
                    {\"name\":\"type\", \"valueString\":\"Patient\"},
                    {\"name\":\"url\", \"valueUri\":\"$aUrl/Patient.ndjson\"}
                  ]
              },
            ]
          }";
          
          echo "the importModeBody is: $importModeBody";
          echo "second echo only";
          var2="BAHH"
          echo "firstVar=$var2" >> $GITHUB_OUTPUT;
          echo "this is the last echo!";
          
      - name: access the var above
        run: |
          echo "the var above is ${{steps.test-folded-style.outputs.output1}}"
          
